openthread/ot-reference-release

- .gitignore
- .gitmodules
- CHANGELOG.txt
- README.md
- script/make-firmware.bash
- script/make-reference-release.bash
This adds support for building efr32 images for Thread 1.3
It also refactors the make-firmware.bash and make-reference-release.bash scripts to allow other platforms to be easily added.
---
- Add ot-efr32 to build script
- Add `ot-efr32` submodule
- Skip Silabs apps in ot-efr32
- Limit efr32 to only brd4166a.
- Refactor `./script/make-firmware.bash`
- If no platform is specified, the script will build all platforms.
If a platform is specified as an argument, the script will build
only that platform
- Allow relative paths for OUTPUT_ROOT when running make-firmware.bash directly
- Add support for downloading nrfutil on MacOS
- Use wildcard to simplify .gitignore
> [build] add support for EFR32 devices on Thread 1.3

- script/bootstrap.bash
- script/make-firmware.bash
- script/make-thci.bash
- script/otbr-setup.bash
This PR includes the following changes:
- Update OpenThread and ot-br-posix to include https://github.com/openthread/openthread/pull/7132
- Revert OpenThread 1.1 version to the previous one (not sure why it was advanced before)
- Rename sdk-nrf master branch to main branch
- Fix nrfutil python package dependency
- Updates THCI script deployment for NCS
Tested manually for ncs, nrf52840 and efre32 platforms (build succeeded). Few changes cherry-picked from @edmont fork.
Fixes: #10
> [build] update building scripts and submodule versions

- script/bootstrap.bash
- script/make-raspbian.bash
This PR fixes a few issues
- Add missing call to `qemu-cleanup.sh`
- Add an exit trap to `make-raspbian.sh` so that the loop devices are always unmounted and detached.
- Without this, any failure that would cause the script to exit prematurely would leave the raspbian loop device attached.
- Fix a spelling error
> [build] add missing qemu-cleanup.sh call

- script/make-firmware.bash
Change "west update" call to narrow and with fetch depth 1. This should speed up update process.
Signed-off-by: Tomasz Kobylarz tomasz.kobylarz@nordicsemi.no
> [ncs] west update call change to narrow

- README.md
Replace link to openthread-users Google Group with link to GitHub OpenThread Discussions, clarify issue reporting links.
> [docs] community discussion changes

- script/bootstrap.bash
In Ubintu 22.10 Ubuntu has changed the name qemu package name to arch specific. This commit addresses that.
> add adaptation for Ubuntu 22.10 package names

- CHANGELOG.txt
- README.md
- script/make-firmware.bash
- script/make-raspbian.bash
- script/otbr-setup.bash
- Submodules are updated to:
- openthread: 6865b83d7fd045b1ea7ee3654b5553a29a967f46 (Apr 6)
- ot-br-posix: d15b080045e96f5515cab7badad3575fa38615a2 (Apr 7)
- ot-nrf528xx: e801931e10bbb76d5a095921c5861bf1a3830561 (Apr 10)
- Updated mDNSResponder version to 1310.80.1
- Added support for REFERENCE_RELEASE_TYPE 1.3.1
- TREL and NAT64 are enabled on 1.3.1, and disabled below 1.3.1
- Some commands to quickly verify TREL in 1.3.1:
- check trel is enabled: `sudo ot-ctl trel`
```
$ sudo ot-ctl trel
Enabled
Done
```
- when connected with another trel enabled device: `sudo ot-ctl trel peers`
```
$ sudo ot-ctl trel peers
| No  | Ext MAC Address  | Ext PAN Id       | IPv6 Socket Address                              |
+-----+------------------+------------------+----------------------------------------- …
```
> Add support for nat64 and trel

- .github/workflows/build.yml
Remove unnecessary files to free up some space. This would help to solve the `System.IO.IOException: No space left on device ` error.
> Remove unnecessary files in GH Actions

- requirements.txt
- script/bootstrap.bash
- script/make-raspbian.bash
- script/make-reference-release.bash
- script/otbr-setup.bash
I think the bootstrap script was originally taken from https://github.com/openthread/ot-br-posix/blob/main/tests/scripts/bootstrap.sh.
Most of the script isn't required since the OTBR build occurs in the mounted Raspberry Pi OS `chroot`, not the host machine. Within the Raspberry Pi OS `chroot`, the OTBR requirements are already being installed in [`script/otbr-setup.bash`](https://github.com/openthread/ot-reference-release/blob/181f96e403c02fdba58bd7209ba03b2064972c26/script/otbr-setup.bash#L178)
This PR removes most of the unnecessary packages and also makes the bootstrap script more flexible, allowing smaller portions of the script to be run via command line arguments
Also, the download of RaspiOS has been moved to [`script/make-raspbian.bash`](https://github.com/openthread/ot-reference …
> [script] refactor `bootstrap` and `make-raspbian.bash`

- .github/workflows/build.yml
- script/make-firmware.bash
- script/otbr-setup.bash
This PR fixes 2 issues:
1. Added DOCKER=1 for otbr bootstrap to skip installing resolvconf.
2. Fix the `expected submodule path 'openthread' not to be a symbolic link` issue caused by make-firmware for nrf52840 creates a symbolic link for openthread submodule. This is not accepted by the git_archive_all tool.
It also adds CI for building 1.3.1 reference release.
> Build for 1.3.1 in CI

- script/make-firmware.bash
- script/otbr-setup.bash
In some environments, `cp` may produce files which have different permissions from the source files. This can fail the build of OTBR. Hence we need to add `-p` option in the command to preserve the permissions.
> [script] perserving the permission when cp openthread files

- CHANGELOG.txt
- script/otbr-setup.bash
* ot-br-posix 7f04c183b04dc490a40bf34f72be7a1b79fa1fbf
* openthread deb35b0c257f6f530cf55c89546772ab867e8041
* ot-nrf528xx f485040d87aa42e834bb24b5bf8115679d972ccd
turn on prefix delegation for 1.4
> Update submodules 'ot-br-posix' and 'openthread' for OTBR PD REF support

- CHANGELOG.txt
openthread f6cee7950d6d4b45ebc9779024b0b456e87159df
ot-br-posix b574b6c2a4ea2ea265f87b908c8ef3f673b27f7f
ot-nrf528xx 6586034ff8377f2d5c87c0f3f8794547c64a4ef2
Include a workaround which disables PD daemon to fix the mDNS disruption
> [pd] bump submodules `ot-br-posix`, `openthread` and `ot-nrf528xx` to include fix for mDNS disruption

- .github/dependabot.yml
- .github/workflows/build.yml
Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact).
1.  **Changes:**
*   Modified the `.github/workflows/build.yml` file.
*   Updated the `uses` line for the `actions/upload-artifact` action from `actions/upload-artifact@v3` to `actions/upload-artifact@v4`.
2.  **Enable Dependabot for GitHub Actions:**
*   A `.github/dependabot.yml` file has been added to the repository.
*   **Reasoning:** This configures Dependabot to automatically check for and create pull requests for updates to GitHub Actions. This ensures that our workflows stay up-to-date and avoids future deprecation issues.
*   **Configuration:** …
> [github-actions] upgrade actions/upload-artifact to v4 and enable dependabot

- CHANGELOG.txt
openthread b1ca77aae9ab0ecfb0f2e6b9f65cbc6ef4c227bc
ot-br-posix 6b9a12e63240f07805b5f26a5b23301ef1913fad
ot-nrf528xx b1b8548704a645f6ed81f5513455865512681efa
Include the fix for where expired DHCPv6 prefix lease is not deprecated correctly
> [pd] bump submodules `ot-br-posix`, `openthread` and `ot-nrf528xx` to include fix for prefix deprecation

- CHANGELOG.txt
- script/make-commissioner.bash
- script/otbr-setup.bash
We've done the migration from python2 to python3 in ot-commissioner so we should remove all python2 occurrences in the project. 
This PR also fixes the build error caused by latest dbus-python. We're sticking it to an older version.
> [script] remove occurrences of python2

- README.md
- script/make-firmware.bash
Add `OPENTHREAD_COMMIT_HASH` flag that when set to a specific sha, forces ncs builds to checkout onto it.
> Allow building ncs with custom OT SHA

- CHANGELOG.txt
Includes change to explicitly specify python3 as the python interpreter: https://github.com/openthread/ot-commissioner/pull/315
> Update ot-commissioner to `f31a98af5`

- CHANGELOG.txt
openthread 4071e328fe846f5ce9e9eff2c5cb291305b50250
ot-br-posix a204b9e4aa3e6ea7f0d57fcf576d2f7ec1ee7f8f
ot-nrf528xx 5d54f48ece480fa23470fb130e5b734fe9568ccd
Include the [update  ](https://github.com/openthread/openthread/pull/11480)  to include new otPlatDnsIsUpstreamQueryAvailable API, which provides a mechanism for the platform to proactively signal the unavailability of upstream DNS. With the API, server could avoid delay in responding to the client when no upstream server available.
> Bump `ot-br-posix`, `openthread` and `ot-nrf528xx` to include new OT API to signal upstream DNS unavailability

- CHANGELOG.txt
openthread ea3a3da0ee13e6813a1547d3c2ec8b7cf30abe2b
ot-br-posix 153e800ccfc8519cca97ba5a10f7f55068628af8
ot-nrf528xx 4966f65866bace00662adc92fad9e14a158ce875
Include the https://github.com/openthread/openthread/pull/11548 to with a fix for DNS resolver to support Link Local address.
> Bump ot-br-posix, openthread and ot-nrf528xx to include the support of RDNSS link-local address

- README.md
- script/make-firmware.bash
- script/otbr-setup.bash
This change formats shell scripts in the repository by running `script/make-pretty shell`.
This uses `shfmt` to enforce a consistent style across all shell scripts. This is a style-only change with no functional impact.
> [script] format shell scripts with make-pretty
